### ISSUE TITLE
PHPStan Type not found

### ISSUE THREAD

**Issue by gauravmak** [rectorphp/rector-book-feedback#38]
# Code Improvement

I think the code on page 67 could be improved:

**Why?**

I am facing the error `[ERROR] Class "Utils\Rector\Rector\ObjectType" not found`.

**I propose this change**

```diff
+use PhpStan\Type\ObjectType;
+
+// ...
+
+public function refactor(Node $node): ?Node
+// ...
```

Thanks!

**Comment by gauravmak** [comment]
The same can be done for the code on pages 70-71.

```diff
+use PhpParser\Node\Expr\PropertyFetch;
```

**Comment by TomasVotruba** [comment]
Hi, thanks for reporting.

I think that's a good idea. I recall having zillion troubles just for missing or present but even wrong import for a wrong node:

![image](https://user-images.githubusercontent.com/924196/124680733-515f7280-dec7-11eb-8988-ef665bad5e49.png)


@matthiasnoback We could extend the book tools to collect used imports and dump them above the code snippet. That would be the easiest way to make code valid, without any modification of existing snippets.

What do you think?

**Comment by marcitqualab** [comment]
I am having the same error. Undefined type 'PhpStan\Type\ObjectType'.
I have added phpstan using composer require --dev phpstan/phpstan and VSCode still does not find this type. 
In general, I am having a lot of issues setting up the right dependencies for a new project. 
Might be good if you provide a project archetype with the right versions resolved. 
Many thanks

**Comment by matthiasnoback** [comment]
@marcitqualab It looks like you're using the correct type, but your IDE doesn't know where the type lives. The class lives inside `phpstan.phar`, is VSCode normally able to find classes in `.phar` files?

**Comment by marcitqualab** [comment]
Hi @matthiasnoback yes, I think it was an open bug in VSCode "intelliphense". In the end, I was able to run the code as described. However, I did not find or missed where is the repo with all the code examples of the book. Is there such a repository? That would make it easier to follow up, investigate and understand the book.

**Comment by matthiasnoback** [comment]
@marcitqualab We don't have such a repository, but it's an interesting idea. We don't yet have the automation to update such a repository with the changes made to the manuscript of the book, so I'm not sure if we can pull it off in a maintainable way.

**Comment by TomasVotruba** [comment]
Such repository would be useful, indeed. Yet we're already fully focused to keep book up to date and improve based on feedback.

I have an idea to turn this into learning experience and also help you, the community around the book.

If you will create repository with final version of examples, well hell you to make it work and improve the CI 👍 What do you think?

**Comment by marcitqualab** [comment]
One benefit of having such a repository is that it will flatten the learning curve as we, the readers, can take some examples and start modifying them from a certain point to test our hypothesis. 
I am happy to help maintain the examples as much as I can do so.

**Comment by matthiasnoback** [comment]
Actually I think we shouldn't copy/paste the final version of the examples to a separate repository manually. We already have the final versions in the book repository as working sub-projects. So ideally we just "cherry-pick" the right folders, and push them to a separate repository.

**Comment by TomasVotruba** [comment]
@matthiasnoback Even better and lazier solution :+1:  I haven't though of that, but I like it.

**Comment by TomasVotruba** [comment]
Looking at the reported issues, the only way to fix it is to use all use imports on every snippet. Yet the snippet is incomplete, it's only part of a class so it fits the book.

So it would crash on another issue like class is missing, or unknown method called etc.

I personally don't trust written text and never copy paste snippets from a book,  unless link to external gist with full raw file  :slightly_smiling_face: 

---

Yet I believe these is a better way to address this, as @matthiasnoback mentioned.

> @marcitqualab We don't have such a repository, but it's an interesting idea. We don't yet have the automation to update such a repository with the changes made to the manuscript of the book, so I'm not sure if we can pull it off in a maintainable way.

I'll think about some automated "publish snippets" command, that would create a repository with at least final and full Rector rules and their test. That way we could give helping hand to devs who want to copy-and-run (I'm one of them :wink: ) and have a always single place they could really rely on.

**Comment by TomasVotruba** [comment]
Coming soon: https://github.com/rectorphp/rector-book-code-examples

**Comment by TomasVotruba** [comment]
Resolved :+1:
