### ISSUE TITLE
Glitch page 54

### ISSUE THREAD

**Issue by neveldo** [rectorphp/rector-book-feedback#51]
# Glitch

I found a glitch on page 54  (book version : "2022-05-05").

In the composer.json snippet, I think that Rector should be in the “require-dev” section instead of the “require” one since Rector has been installed with the command “composer require rector/rector --dev” when following the instructions from the previous page.

**I propose this change**

```diff
-    "require": {
+    "require-dev": {
```

Thanks!

**Comment by TomasVotruba** [comment]
Could you be more precise where exactly this snippet is? The "require-dev" is pretty hard to find, as in many places.

What text/code is around this one?

**Comment by TomasVotruba** [comment]
Thing is, the page number does not help, as we have a repository with single huge markdown text :)  the page number change based on text and final generated book.

If you could provide screen or 3-5 sentestes before and after, that would help :+1:

**Comment by neveldo** [comment]
I wasn't aware of that, got it ! This composer snippet appears  in the part "Where to Store Your Rule Classes?", right below this sentence : 

> When you use the namespace Utils\Rector\Rector for your rule classes and store them in utils/rector/src/Rector, then the "autoload-dev" section in your composer.json file should look like this:

And above this one : 

> After changing settings for auto-loading in composer.json you should always run:

**Comment by TomasVotruba** [comment]
Thanks, I've just update the book with this fix :+1:
