### ISSUE TITLE
Please, add instructions to where to place the code and how to test it

### ISSUE THREAD

**Issue by realtebo** [rectorphp/rector-book-feedback#62]
# Text Improvement

I think the text on chapter "Creating your first rector rule" could be improved:

**Why?**

Because the code is no way 'ready to run'. For example you write code about "Usercontroller" class, and not give us instructions where to place the file at all. 

I see where to place this 

utils/rector/src/Rector/UseRequestRequestGetRector.php

but this cannot run without include any sort of autoloader for composer classes, am I right?

Then we create before.php . Where ?

some pages after, you say 

"Assuming that your project files are in src/, ... "

and so I move before.php into src. ok . 

but anyway, without requiring the autoloder it not works

More after, appears a file named "app/Controller/UserController.php" 

Damn ... are not we using before.php in src directory ? 

so, again, confusion ...

**I propose this change**

you should try to read this chapter from a newbie perspective, following your code and asking "do the reader have all needed info to follow and run code  ?"

Thanks!

**Comment by TomasVotruba** [comment]
Hi, thanks for feedback :+1: 

We've added a "custom-rule" rule command, that solves this and avoid hard thinking. It generates all the basic file structure for you :wink: 

It will be also further improved by: 
https://github.com/rectorphp/rector-book-feedback/issues/38
